// LIVE contact presence for Eitaa Web. One bridge, one call, with proof.
//
// WHY THIS EXISTS
// ---------------
// contacts.getContacts hands back a snapshot frozen at the instant the session
// came up. Measured: the same newest last-seen (19:54:12) returned across 105
// minutes, a 45-second wait, and a full page reload, on an account where 208
// contacts had been seen inside 24 hours.
//
// Four wrong explanations were ruled out before the right one:
//   * host clock skew        -> tweb's serverTimeOffset read 0s. Clock is exact.
//   * our page holding it    -> a full reload returned the identical snapshot.
//   * Eitaa pushing presence -> processUpdateMessage counted ZERO updates of any
//                               kind in 45s. The 9 "presence events" seen on
//                               rootScope were generated by our OWN getContacts
//                               calls feeding saveApiUsers, not by the server.
//   * the store being fresh  -> reading appUsersManager gained 9 minutes on data
//                               96 minutes old, and that 9 minutes was exactly
//                               the online contacts' expires being converted to
//                               was_online locally. Zero new information.
//
// What is left is the actual cause: no update traffic reaches this page, so
// invokeApi is answering from tweb's IndexedDB cache. The page is logged in and
// looks healthy while being effectively offline.
//
// WHAT THIS DOES
// --------------
//   1. updates.getState  -- returns the SERVER's current date. A live reply both
//      proves the socket works and yields the true clock offset by measurement.
//      This is the check that should have come first, before any theorising.
//   2. Un-hide the page. tweb suspends its update loop while the document is
//      hidden, and under xvfb it is hidden forever, which is why no updates ever
//      arrived. document.hidden/visibilityState are overridden and a
//      visibilitychange is dispatched.
//   3. account.updateStatus({offline:false}) to restart the update loop.
//   4. users.getUsers in batches, which returns CURRENT user objects rather than
//      a cached contacts blob. Ids come from appUsersManager's OWN contactsList:
//      passing ids in from Python is what produced PEER_ID_INVALID for an entire
//      batch, because the store's key type is not what we reconstructed.
//   5. Report freshness as evidence, not as a claim -- newest last-seen, its age
//      against the SERVER's clock, and every batch that failed with its error.
//      A caller must be able to tell "verified live" from "we hope so".
//
//   window.__MKWL_livePresence({ batch: 100 }) -> see the return shape below.
//
// Read-only for contact data. The one side effect is marking OUR OWN account
// online via updateStatus, which is unavoidable: a client that reports itself
// offline is not sent updates.
(() => {
  if (window.__MKWL_livePresence) return;

  function errStr(e) {
    try { return String((e && (e.type || e.error_message || e.code || e.message)) || e); }
    catch (x) { return "ERR"; }
  }

  function titleOf(u) {
    const first = (u.first_name || "").trim();
    const last = (u.last_name || "").trim();
    const name = (first + " " + last).trim();
    if (name) return name.slice(0, 80);
    if (u.username) return String(u.username).slice(0, 80);
    if (u.phone) return String(u.phone).slice(0, 80);
    return String(u.id);
  }

  // tweb pauses its update loop when the document is hidden. Under xvfb with no
  // real window the page is hidden for its entire life, so the loop never runs
  // and invokeApi quietly serves cache. Overriding the getters is enough; tweb
  // reads them rather than caching the value.
  function unhide() {
    const before = { hidden: document.hidden,
                     state: document.visibilityState };
    try {
      Object.defineProperty(document, "hidden",
        { configurable: true, get: () => false });
      Object.defineProperty(document, "visibilityState",
        { configurable: true, get: () => "visible" });
      Object.defineProperty(document, "webkitHidden",
        { configurable: true, get: () => false });
      document.dispatchEvent(new Event("visibilitychange"));
      window.dispatchEvent(new Event("focus"));
      if (typeof window.focus === "function") window.focus();
    } catch (e) {
      return { ok: false, before: before, code: errStr(e) };
    }
    return { ok: true, before: before,
             after: { hidden: document.hidden,
                      state: document.visibilityState } };
  }

  //: Pull the contact ids out of the store itself. Every id we invented or
  //: round-tripped through Python was rejected by the API; these are the values
  //: appUsersManager already uses as keys, so they are the only ones guaranteed
  //: to build a valid inputUser.
  function storeContactIds(AUM) {
    const ids = [];
    try {
      const cl = AUM.contactsList || AUM.contacts;
      if (cl && typeof cl.forEach === "function") cl.forEach((v) => ids.push(v));
    } catch (e) { /* reported by the caller as an empty roster */ }
    return ids;
  }

  function readStatus(u) {
    const st = u && u.status;
    return {
      status: (st && st._) ? String(st._) : "",
      was_online: (st && typeof st.was_online === "number") ? st.was_online : null,
      expires: (st && typeof st.expires === "number") ? st.expires : null
    };
  }

  window.__MKWL_livePresence = async function (opts) {
    opts = opts || {};
    const batchSize = Math.max(1, Math.min(200, opts.batch || 100));
    const AM = window.apiManager;
    const AUM = window.appUsersManager;
    if (!AM || !AM.invokeApi) return { ok: false, code: "no invokeApi" };
    if (!AUM) return { ok: false, code: "no appUsersManager" };

    const out = {
      ok: true, errors: [], page_now: Math.floor(Date.now() / 1000)
    };

    // 1. Prove the connection, and get the server's clock.
    try {
      const t0 = Date.now();
      const st = await AM.invokeApi("updates.getState", {});
      out.getstate_ms = Date.now() - t0;
      out.server_date = (st && typeof st.date === "number") ? st.date : null;
      out.pts = (st && st.pts) || null;
      out.connected = out.server_date != null;
    } catch (e) {
      out.connected = false;
      out.errors.push("updates.getState:" + errStr(e));
    }
    const now = out.server_date || out.page_now;
    out.clock_offset = out.server_date ? (out.page_now - out.server_date) : null;

    // 2 + 3. Wake the page up so the update loop can run.
    out.unhide = unhide();
    try {
      await AM.invokeApi("account.updateStatus", { offline: false });
      out.marked_online = true;
    } catch (e) {
      out.marked_online = false;
      out.errors.push("account.updateStatus:" + errStr(e));
    }

    // 4. Fresh user objects, batched, ids from the store.
    const ids = storeContactIds(AUM);
    out.store_ids = ids.length;
    if (!ids.length) {
      out.ok = false;
      out.code = "appUsersManager holds no contact ids";
      return out;
    }

    const getInput = AUM.getUserInput || AUM.getUserInputById;
    if (typeof getInput !== "function") {
      out.ok = false;
      out.code = "appUsersManager has no getUserInput";
      return out;
    }

    const roster = [];
    let batches = 0, failedBatches = 0, unbuildable = 0;
    const t1 = Date.now();
    for (let i = 0; i < ids.length; i += batchSize) {
      const slice = ids.slice(i, i + batchSize);
      const input = [];
      for (let j = 0; j < slice.length; j++) {
        try {
          const inp = getInput.call(AUM, slice[j]);
          if (inp && inp._ && inp._ !== "inputUserEmpty") input.push(inp);
          else unbuildable++;
        } catch (e) { unbuildable++; }
      }
      if (!input.length) { failedBatches++; continue; }
      batches++;
      let users = null;
      try {
        users = await AM.invokeApi("users.getUsers", { id: input });
      } catch (e) {
        failedBatches++;
        // Never swallow: the batch index and the real error are both recorded so
        // a partial roster can be told apart from a complete one.
        out.errors.push("users.getUsers[" + i + ".." + (i + input.length) + "]:"
                        + errStr(e));
        continue;
      }
      for (let k = 0; k < (users || []).length; k++) {
        const u = users[k];
        if (!u || u.id == null) continue;
        const f = u.pFlags || {};
        if (f.self || f.deleted || f.bot) continue;
        if (!u.access_hash) continue;
        const s = readStatus(u);
        roster.push({
          peer_id: String(u.id), access_hash: String(u.access_hash),
          title: titleOf(u), username: u.username ? String(u.username) : "",
          phone: u.phone ? String(u.phone) : "",
          status: s.status, was_online: s.was_online, expires: s.expires
        });
      }
    }
    out.fetch_ms = Date.now() - t1;
    out.batches = batches;
    out.failed_batches = failedBatches;
    out.unbuildable_ids = unbuildable;
    out.source = "users.getUsers";

    // 5. Freshness evidence, measured against the SERVER's clock where we have it.
    let newest = 0, online = 0;
    for (let i = 0; i < roster.length; i++) {
      const r = roster[i];
      if (r.status === "userStatusOnline") online++;
      if (typeof r.was_online === "number" && r.was_online > newest)
        newest = r.was_online;
    }
    out.roster = roster;
    out.count = roster.length;
    out.newest_was_online = newest || null;
    out.presence_age_sec = newest ? Math.max(0, now - newest) : null;
    out.online_count = online;
    out.server_now = now;

    if (!roster.length) {
      out.ok = false;
      out.code = "users.getUsers returned no usable contacts"
                 + (out.errors.length ? " (" + out.errors[0] + ")" : "");
    }
    return out;
  };
})();
