// LIVE contact presence for Eitaa Web. One bridge, one call, with proof.
//
// WHY THIS EXISTS
// ---------------
// contacts.getContacts hands back a snapshot frozen at the instant the session
// came up. Measured: the same newest last-seen (19:54:12) returned across 105
// minutes, a 45-second wait, and a full page reload, on an account where 208
// contacts had been seen inside 24 hours.
//
// Four wrong explanations were ruled out before the right one:
//   * host clock skew        -> tweb's serverTimeOffset read 0s. Clock is exact.
//   * our page holding it    -> a full reload returned the identical snapshot.
//   * Eitaa pushing presence -> processUpdateMessage counted ZERO updates of any
//                               kind in 45s. The 9 "presence events" seen on
//                               rootScope were generated by our OWN getContacts
//                               calls feeding saveApiUsers, not by the server.
//   * the store being fresh  -> reading appUsersManager gained 9 minutes on data
//                               96 minutes old, and that 9 minutes was exactly
//                               the online contacts' expires being converted to
//                               was_online locally. Zero new information.
//
// What is left is the actual cause: no update traffic reaches this page, so
// invokeApi is answering from tweb's IndexedDB cache. The page is logged in and
// looks healthy while being effectively offline.
//
// WHAT THIS DOES
// --------------
//   1. updates.getState  -- returns the SERVER's current date. A live reply both
//      proves the socket works and yields the true clock offset by measurement.
//      This is the check that should have come first, before any theorising.
//   2. Un-hide the page. tweb suspends its update loop while the document is
//      hidden, and under xvfb it is hidden forever, which is why no updates ever
//      arrived. document.hidden/visibilityState are overridden and a
//      visibilitychange is dispatched.
//   3. account.updateStatus({offline:false}) to restart the update loop.
//   4. users.getUsers in batches, which returns CURRENT user objects rather than
//      a cached contacts blob. Ids come from appUsersManager's OWN contactsList:
//      passing ids in from Python is what produced PEER_ID_INVALID for an entire
//      batch, because the store's key type is not what we reconstructed.
//   5. Report freshness as evidence, not as a claim -- newest last-seen, its age
//      against the SERVER's clock, and every batch that failed with its error.
//      A caller must be able to tell "verified live" from "we hope so".
//
//   window.__MKWL_livePresence({ batch: 100 }) -> see the return shape below.
//
// Read-only for contact data. The one side effect is marking OUR OWN account
// online via updateStatus, which is unavoidable: a client that reports itself
// offline is not sent updates.
(() => {
  if (window.__MKWL_livePresence) return;

  function errStr(e) {
    try { return String((e && (e.type || e.error_message || e.code || e.message)) || e); }
    catch (x) { return "ERR"; }
  }

  function titleOf(u) {
    const first = (u.first_name || "").trim();
    const last = (u.last_name || "").trim();
    const name = (first + " " + last).trim();
    if (name) return name.slice(0, 80);
    if (u.username) return String(u.username).slice(0, 80);
    if (u.phone) return String(u.phone).slice(0, 80);
    return String(u.id);
  }

  // tweb pauses its update loop when the document is hidden. Under xvfb with no
  // real window the page is hidden for its entire life, so the loop never runs
  // and invokeApi quietly serves cache. Overriding the getters is enough; tweb
  // reads them rather than caching the value.
  function unhide() {
    const before = { hidden: document.hidden,
                     state: document.visibilityState };
    try {
      Object.defineProperty(document, "hidden",
        { configurable: true, get: () => false });
      Object.defineProperty(document, "visibilityState",
        { configurable: true, get: () => "visible" });
      Object.defineProperty(document, "webkitHidden",
        { configurable: true, get: () => false });
      document.dispatchEvent(new Event("visibilitychange"));
      window.dispatchEvent(new Event("focus"));
      if (typeof window.focus === "function") window.focus();
    } catch (e) {
      return { ok: false, before: before, code: errStr(e) };
    }
    return { ok: true, before: before,
             after: { hidden: document.hidden,
                      state: document.visibilityState } };
  }

  //: Pull the contact ids out of the store itself. Every id we invented or
  //: round-tripped through Python was rejected by the API; these are the values
  //: appUsersManager already uses as keys, so they are the only ones guaranteed
  //: to build a valid inputUser.
  function storeContactIds(AUM) {
    const ids = [];
    try {
      const cl = AUM.contactsList || AUM.contacts;
      if (cl && typeof cl.forEach === "function") cl.forEach((v) => ids.push(v));
    } catch (e) { /* reported by the caller as an empty roster */ }
    return ids;
  }

  function readStatus(u) {
    const st = u && u.status;
    return {
      status: (st && st._) ? String(st._) : "",
      was_online: (st && typeof st.was_online === "number") ? st.was_online : null,
      expires: (st && typeof st.expires === "number") ? st.expires : null
    };
  }

  //: users.getUsers is declared as Vector<User>, but 10 of 11 batches came back
  //: "successful" and yielded ZERO usable contacts, which means the reply was not
  //: the bare array assumed. Rather than guess again, every plausible shape is
  //: accepted and the shape actually seen is REPORTED, so a third wrong guess is
  //: impossible.
  function asUserArray(x) {
    if (Array.isArray(x)) return x;
    if (x && Array.isArray(x.users)) return x.users;
    if (x && typeof x === "object") {
      const vals = [];
      const keys = Object.keys(x);
      for (let i = 0; i < keys.length; i++) {
        const v = x[keys[i]];
        if (v && typeof v === "object" && v.id != null) vals.push(v);
      }
      if (vals.length) return vals;
    }
    return [];
  }

  function shapeOf(x) {
    if (x == null) return String(x);
    if (Array.isArray(x)) return "array[" + x.length + "]";
    if (typeof x !== "object") return typeof x;
    return "object{" + Object.keys(x).slice(0, 10).join(",") + "}";
  }

  window.__MKWL_livePresence = async function (opts) {
    opts = opts || {};
    const batchSize = Math.max(1, Math.min(200, opts.batch || 100));
    const AM = window.apiManager;
    const AUM = window.appUsersManager;
    if (!AM || !AM.invokeApi) return { ok: false, code: "no invokeApi" };
    if (!AUM) return { ok: false, code: "no appUsersManager" };

    const out = {
      ok: true, errors: [], page_now: Math.floor(Date.now() / 1000)
    };

    // 0. Un-hide FIRST. Every call below wants tweb's update loop already
    //    running; doing this after the API calls would leave the first ones
    //    served from cache exactly as before.
    out.unhide = unhide();

    // 1. Prove the connection, and get the server's clock.
    try {
      const t0 = Date.now();
      const st = await AM.invokeApi("updates.getState", {});
      out.getstate_ms = Date.now() - t0;
      out.server_date = (st && typeof st.date === "number") ? st.date : null;
      out.pts = (st && st.pts) || null;
      out.connected = out.server_date != null;
    } catch (e) {
      out.connected = false;
      out.errors.push("updates.getState:" + errStr(e));
    }
    const now = out.server_date || out.page_now;
    out.clock_offset = out.server_date ? (out.page_now - out.server_date) : null;

    // 2 + 3. Tell the server we are here, so it starts sending updates.
    try {
      await AM.invokeApi("account.updateStatus", { offline: false });
      out.marked_online = true;
    } catch (e) {
      out.marked_online = false;
      out.errors.push("account.updateStatus:" + errStr(e));
    }

    // 4. Fresh user objects, batched, ids from the store.
    //
    // The store is EMPTY until something loads contacts, and this bridge runs
    // before anything else does -- which is why the first live run failed
    // immediately in 0.39s. So seed it with one contacts.getContacts.
    //
    // That is not a contradiction of this file's whole premise. getContacts is
    // useless for PRESENCE, which is what it was measured being frozen on, but
    // it is perfectly good for the ROSTER: ids and access_hashes do not go
    // stale. The statuses are then re-read fresh via users.getUsers below.
    const base = {};                 // peer_id -> identity + last known status
    const rawInput = {};             // peer_id -> inputUser, unmodified values
    let ids = storeContactIds(AUM);
    out.id_source = "store contactsList";
    if (!ids.length) {
      try {
        const t0 = Date.now();
        const c = await AM.invokeApi("contacts.getContacts", { hash: 0 });
        const seeded = (c && c.users) || [];
        out.seed_ms = Date.now() - t0;
        out.seeded_users = seeded.length;
        // Keep the seed as the IDENTITY base. Ids, access_hashes and names do
        // not go stale, so only the STATUS needs refreshing on top -- and this
        // means one failed batch costs 6 statuses, not the whole run.
        for (let s = 0; s < seeded.length; s++) {
          const u = seeded[s];
          if (!u || u.id == null) continue;
          const f = u.pFlags || {};
          if (f.self || f.deleted || f.bot) continue;
          if (!u.access_hash) continue;
          const st = readStatus(u);
          // The inputUser is built from the access_hash EXACTLY as the API
          // handed it over -- same object, no String() and no round trip
          // through Python. access_hash is a 64-bit value; stringifying it and
          // handing the string back is what produced PEER_ID_INVALID on the
          // first attempt, and relying on getUserInput instead only moved the
          // problem to a store that was never populated.
          rawInput[String(u.id)] = { _: "inputUser", user_id: u.id,
                                     access_hash: u.access_hash };
          base[String(u.id)] = {
            peer_id: String(u.id), access_hash: String(u.access_hash),
            title: titleOf(u), username: u.username ? String(u.username) : "",
            phone: u.phone ? String(u.phone) : "",
            status: st.status, was_online: st.was_online, expires: st.expires,
            fresh: false
          };
        }
        // NOT `if (AUM.saveApiUsers)` with nothing in the else. That silently
        // skipped the whole step when the method is absent under a different
        // name, and the absence then showed up far away as an empty
        // users.getUsers reply -- a swallowed failure diagnosed as an API
        // problem. Whether it ran is now recorded either way.
        const save = AUM.saveApiUsers || AUM.saveApiUsersUnsafe;
        if (typeof save === "function") {
          try { save.call(AUM, seeded); out.saved_to_store = true; }
          catch (e) {
            out.saved_to_store = false;
            out.errors.push("saveApiUsers:" + errStr(e));
          }
        } else {
          out.saved_to_store = false;
          out.errors.push("appUsersManager has no saveApiUsers — the store was "
                          + "never populated, so getUserInput cannot build a "
                          + "valid inputUser");
        }
        ids = storeContactIds(AUM);
        out.id_source = "store after seeding";
        if (!ids.length) {
          // Last resort: the ids straight out of the seed reply. Less reliable
          // than the store's own keys, so it is recorded when used.
          ids = seeded.filter((u) => u && u.id != null).map((u) => u.id);
          out.id_source = "seed reply (store still empty)";
        }
      } catch (e) {
        out.errors.push("seed contacts.getContacts:" + errStr(e));
      }
    }
    out.store_ids = ids.length;
    if (!ids.length) {
      out.ok = false;
      out.code = "no contact ids: store is empty and seeding failed"
                 + (out.errors.length ? " (" + out.errors.join("; ") + ")" : "");
      return out;
    }

    const getInput = AUM.getUserInput || AUM.getUserInputById;
    if (typeof getInput !== "function") {
      out.ok = false;
      out.code = "appUsersManager has no getUserInput";
      return out;
    }

    // A ONE-USER PROBE, before spending eleven round trips. The previous run
    // made 11 calls, got ten empty arrays and one PEER_ID_INVALID, and still
    // could not say WHICH way of building the input was wrong. This tries both
    // on a single contact and reports each outcome separately, so one run is
    // enough to know.
    const probeKeys = Object.keys(rawInput);
    if (probeKeys.length) {
      const k0 = probeKeys[0];
      out.probe = {};
      try {
        const r = await AM.invokeApi("users.getUsers", { id: [rawInput[k0]] });
        const arr = asUserArray(r);
        out.probe.raw_access_hash = arr.length
          ? "OK (" + arr.length + " user, status="
            + ((arr[0] && arr[0].status && arr[0].status._) || "none") + ")"
          : "EMPTY reply, shape " + shapeOf(r);
      } catch (e) {
        out.probe.raw_access_hash = "ERROR " + errStr(e);
      }
      if (typeof getInput === "function") {
        try {
          const inp = getInput.call(AUM, ids[0]);
          const r = await AM.invokeApi("users.getUsers", { id: [inp] });
          const arr = asUserArray(r);
          out.probe.getUserInput = arr.length
            ? "OK (" + arr.length + " user)"
            : "EMPTY reply, shape " + shapeOf(r);
          out.probe.getUserInput_shape = shapeOf(inp);
        } catch (e) {
          out.probe.getUserInput = "ERROR " + errStr(e);
        }
      }
    }

    // Whichever input style the probe proved, use it. Preferring the raw
    // access_hash because it needs no populated store to be correct.
    const useRaw = !!(out.probe && String(out.probe.raw_access_hash || "")
                                     .indexOf("OK") === 0);
    out.input_style = useRaw ? "raw access_hash from the seed reply"
                             : "appUsersManager.getUserInput";

    let batches = 0, failedBatches = 0, unbuildable = 0;
    let refreshed = 0, emptyReplies = 0;
    const t1 = Date.now();
    for (let i = 0; i < ids.length; i += batchSize) {
      const slice = ids.slice(i, i + batchSize);
      const input = [];
      for (let j = 0; j < slice.length; j++) {
        const key = String(slice[j]);
        let inp = null;
        if (useRaw && rawInput[key]) {
          inp = rawInput[key];
        } else {
          try { inp = getInput.call(AUM, slice[j]); } catch (e) { inp = null; }
          if (!inp && rawInput[key]) inp = rawInput[key];
        }
        if (inp && inp._ && inp._ !== "inputUserEmpty") input.push(inp);
        else unbuildable++;
      }
      if (!input.length) { failedBatches++; continue; }
      batches++;
      let reply = null;
      try {
        reply = await AM.invokeApi("users.getUsers", { id: input });
      } catch (e) {
        failedBatches++;
        // Never swallow: the batch range and the real error are both recorded, so
        // a partial refresh can never be mistaken for a complete one.
        out.errors.push("users.getUsers[" + i + ".." + (i + input.length) + "]:"
                        + errStr(e));
        continue;
      }
      if (!out.reply_shape) out.reply_shape = shapeOf(reply);
      const users = asUserArray(reply);
      if (!users.length) {
        emptyReplies++;
        if (!out.empty_reply_shape) out.empty_reply_shape = shapeOf(reply);
        continue;
      }
      // STATUS ONLY. Identity stays as seeded, so a user arriving here without
      // an access_hash is still addressable instead of being silently dropped --
      // which is how ten successful batches produced an empty roster.
      for (let k = 0; k < users.length; k++) {
        const u = users[k];
        if (!u || u.id == null) continue;
        const key = String(u.id);
        const s = readStatus(u);
        if (!s.status) continue;
        if (base[key]) {
          base[key].status = s.status;
          base[key].was_online = s.was_online;
          base[key].expires = s.expires;
          base[key].fresh = true;
          refreshed++;
        } else {
          const f = u.pFlags || {};
          if (f.self || f.deleted || f.bot) continue;
          if (!u.access_hash) continue;
          base[key] = {
            peer_id: key, access_hash: String(u.access_hash), title: titleOf(u),
            username: u.username ? String(u.username) : "",
            phone: u.phone ? String(u.phone) : "",
            status: s.status, was_online: s.was_online, expires: s.expires,
            fresh: true
          };
          refreshed++;
        }
      }
    }
    out.fetch_ms = Date.now() - t1;
    out.batches = batches;
    out.failed_batches = failedBatches;
    out.unbuildable_ids = unbuildable;
    out.empty_replies = emptyReplies;
    out.refreshed = refreshed;
    out.source = "users.getUsers";

    const roster = [];
    const keys = Object.keys(base);
    for (let i = 0; i < keys.length; i++) roster.push(base[keys[i]]);

    // 5. Freshness measured ONLY on the statuses actually refreshed. Deriving it
    //    from the seeded ones would read the frozen snapshot's age back as proof
    //    of freshness, which is circular.
    let newest = 0, online = 0, freshCount = 0;
    for (let i = 0; i < roster.length; i++) {
      const r = roster[i];
      if (r.status === "userStatusOnline") online++;
      if (!r.fresh) continue;
      freshCount++;
      if (typeof r.was_online === "number" && r.was_online > newest)
        newest = r.was_online;
      if (typeof r.expires === "number" && r.expires > newest) newest = r.expires;
    }
    out.roster = roster;
    out.count = roster.length;
    out.fresh_count = freshCount;
    out.coverage_pct = roster.length
      ? Math.round(freshCount * 1000 / roster.length) / 10 : 0;
    out.newest_was_online = newest || null;
    out.presence_age_sec = (freshCount && newest) ? Math.max(0, now - newest) : null;
    out.online_count = online;
    out.server_now = now;

    // A partial refresh is a USABLE result: 1,000 of 1,006 fresh statuses is not
    // a failure, and the previous version threw exactly that away over one bad
    // batch of six. Only a roster with nothing in it is fatal; low coverage is
    // reported and left to the freshness gate to judge.
    if (!roster.length) {
      out.ok = false;
      out.code = "no usable contacts at all"
                 + (out.errors.length ? " (" + out.errors.join("; ") + ")" : "")
                 + (out.reply_shape ? " [reply shape: " + out.reply_shape + "]" : "");
    } else if (!freshCount) {
      out.ok = false;
      out.code = "roster built (" + roster.length + ") but NOT ONE status was "
                 + "refreshed, so it is only the frozen snapshot"
                 + (out.empty_reply_shape
                    ? " [replies yielded no users; shape: "
                      + out.empty_reply_shape + "]" : "")
                 + (out.errors.length ? " (" + out.errors[0] + ")" : "");
    }
    return out;
  };
})();
